package com.example.demo.entity;

import lombok.Data;

import java.io.Serializable;
@Data
public class Car implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carid
     *
     * @mbggenerated Tue May 19 16:01:44 CST 2020
     */
    private Integer carid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carname
     *
     * @mbggenerated Tue May 19 16:01:44 CST 2020
     */
    private String carname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.uid
     *
     * @mbggenerated Tue May 19 16:01:44 CST 2020
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carid
     *
     * @return the value of car.carid
     *
     * @mbggenerated Tue May 19 16:01:44 CST 2020
     */
    public Integer getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carid
     *
     * @param carid the value for car.carid
     *
     * @mbggenerated Tue May 19 16:01:44 CST 2020
     */
    public void setCarid(Integer carid) {
        this.carid = carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carname
     *
     * @return the value of car.carname
     *
     * @mbggenerated Tue May 19 16:01:44 CST 2020
     */
    public String getCarname() {
        return carname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carname
     *
     * @param carname the value for car.carname
     *
     * @mbggenerated Tue May 19 16:01:44 CST 2020
     */
    public void setCarname(String carname) {
        this.carname = carname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.uid
     *
     * @return the value of car.uid
     *
     * @mbggenerated Tue May 19 16:01:44 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.uid
     *
     * @param uid the value for car.uid
     *
     * @mbggenerated Tue May 19 16:01:44 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}