package com.shiro2.mapper;

import com.shiro2.entity.Roletree;
import com.shiro2.entity.RoletreeExample;
import com.shiro2.entity.RoletreeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoletreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Wed May 27 14:14:08 CST 2020
     */
    int countByExample(RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Wed May 27 14:14:08 CST 2020
     */
    int deleteByExample(RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Wed May 27 14:14:08 CST 2020
     */
    int deleteByPrimaryKey(RoletreeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Wed May 27 14:14:08 CST 2020
     */
    int insert(Roletree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Wed May 27 14:14:08 CST 2020
     */
    int insertSelective(Roletree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Wed May 27 14:14:08 CST 2020
     */
    List<Roletree> selectByExample(RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Wed May 27 14:14:08 CST 2020
     */
    Roletree selectByPrimaryKey(RoletreeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Wed May 27 14:14:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") Roletree record, @Param("example") RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Wed May 27 14:14:08 CST 2020
     */
    int updateByExample(@Param("record") Roletree record, @Param("example") RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Wed May 27 14:14:08 CST 2020
     */
    int updateByPrimaryKeySelective(Roletree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Wed May 27 14:14:08 CST 2020
     */
    int updateByPrimaryKey(Roletree record);
}